// Action Types
export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';

// Others
export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
